# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('NUL', 'Select a category'), ('Arts & Craft', 'Arts & Craft'), ('music', 'Music'), ('games', 'Games'), ('collectors', 'Collectors'), ('sport and outdoors', 'Sport & outdoors'), ('academic', 'Academic & Educational'), ('other', 'other')], max_length=100)),
                ('date_added', models.DateTimeField()),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
            ],
            options={
                'verbose_name_plural': 'Hobby Products',
                'ordering': ['-id'],
            },
        ),
    ]
