# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hobby_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('NUL', 'Select a category'), ('Arts & Craft', 'Arts & Craft'), ('music', 'Music'), ('games', 'Games'), ('collectors', 'Collectors'), ('sport and outdoors', 'Sport & outdoors'), ('academic', 'Academic & Educational'), ('other', 'other')], max_length=100)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Hobby Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hobby_product.hobby_product')),
            ],
        ),
    ]
