# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_product', '0004_remove_hobby_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby_product',
            name='category',
            field=models.CharField(choices=[('NUL', 'Select a category'), ('art', 'Art'), ('music', 'Music'), ('games', 'Games'), ('collectors', 'Collectors'), ('sport', 'Sport'), ('academic', 'Academic & Educational'), ('other', 'other')], max_length=100),
        ),
    ]
