# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-27 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_product', '0005_auto_20200628_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby_product',
            name='category',
            field=models.CharField(choices=[('school', 'Select a category'), ('rent', 'rent'), ('course', 'course'), ('weekend', 'weekend'), ('groups', 'groups'), ('private', 'private'), ('school', 'school')], max_length=100),
        ),
    ]
