# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('min_value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('final_value', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Auctions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date', models.DateTimeField(verbose_name='when the bid was made')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
        migrations.CreateModel(
            name='hobby_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('NUL', 'Select a category'), ('music', 'Music'), ('games', 'Games'), ('collectors', 'Collectors'), ('sport and outdoors', 'Sport & outdoors'), ('academic', 'Academic & Educational'), ('other', 'other')], max_length=100)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Hobby Products',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='hobby_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.hobby_product'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('(deleted)'), related_name='auction_winner', related_query_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
