# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_product', '0004_remove_hobby_product_reviews'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hobby_product.hobby_product'),
        ),
    ]
